packages:
  - "apps/*"
  - "packages/*"

catalog:
  react: 19.2.1
  react-dom: 19.2.1
  "@types/react": 19.2.7
  "@types/react-dom": 19.2.3
  "@types/node": 24.10.1
  typescript: 5.9.3
  vite: 7.2.6
  lucide-react: 0.555.0
  "@tanstack/react-query": 5.90.12
  "@base-ui/react": 1.0.0
