/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as SystemRouteRouteImport } from './routes/_system/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as SystemIndexRouteImport } from './routes/_system/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as SystemUsersMeRouteImport } from './routes/_system/users/me'
import { Route as SystemTeamsTeamIdIndexRouteImport } from './routes/_system/teams/$teamId/index'
import { Route as SystemTeamsTeamIdSettingsRouteImport } from './routes/_system/teams/$teamId/settings'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRouteRoute = SystemRouteRouteImport.update({
  id: '/_system',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const SystemIndexRoute = SystemIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SystemRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const SystemUsersMeRoute = SystemUsersMeRouteImport.update({
  id: '/users/me',
  path: '/users/me',
  getParentRoute: () => SystemRouteRoute,
} as any)
const SystemTeamsTeamIdIndexRoute = SystemTeamsTeamIdIndexRouteImport.update({
  id: '/teams/$teamId/',
  path: '/teams/$teamId/',
  getParentRoute: () => SystemRouteRoute,
} as any)
const SystemTeamsTeamIdSettingsRoute =
  SystemTeamsTeamIdSettingsRouteImport.update({
    id: '/teams/$teamId/settings',
    path: '/teams/$teamId/settings',
    getParentRoute: () => SystemRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof SystemIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/users/me': typeof SystemUsersMeRoute
  '/teams/$teamId/settings': typeof SystemTeamsTeamIdSettingsRoute
  '/teams/$teamId': typeof SystemTeamsTeamIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof SystemIndexRoute
  '/auth': typeof AuthIndexRoute
  '/users/me': typeof SystemUsersMeRoute
  '/teams/$teamId/settings': typeof SystemTeamsTeamIdSettingsRoute
  '/teams/$teamId': typeof SystemTeamsTeamIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_system': typeof SystemRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/register': typeof AuthRegisterRoute
  '/_system/': typeof SystemIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_system/users/me': typeof SystemUsersMeRoute
  '/_system/teams/$teamId/settings': typeof SystemTeamsTeamIdSettingsRoute
  '/_system/teams/$teamId/': typeof SystemTeamsTeamIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/auth/register'
    | '/'
    | '/auth/'
    | '/users/me'
    | '/teams/$teamId/settings'
    | '/teams/$teamId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/register'
    | '/'
    | '/auth'
    | '/users/me'
    | '/teams/$teamId/settings'
    | '/teams/$teamId'
  id:
    | '__root__'
    | '/_system'
    | '/auth'
    | '/auth/register'
    | '/_system/'
    | '/auth/'
    | '/_system/users/me'
    | '/_system/teams/$teamId/settings'
    | '/_system/teams/$teamId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SystemRouteRoute: typeof SystemRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_system': {
      id: '/_system'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SystemRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_system/': {
      id: '/_system/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SystemIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_system/users/me': {
      id: '/_system/users/me'
      path: '/users/me'
      fullPath: '/users/me'
      preLoaderRoute: typeof SystemUsersMeRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/_system/teams/$teamId/': {
      id: '/_system/teams/$teamId/'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof SystemTeamsTeamIdIndexRouteImport
      parentRoute: typeof SystemRouteRoute
    }
    '/_system/teams/$teamId/settings': {
      id: '/_system/teams/$teamId/settings'
      path: '/teams/$teamId/settings'
      fullPath: '/teams/$teamId/settings'
      preLoaderRoute: typeof SystemTeamsTeamIdSettingsRouteImport
      parentRoute: typeof SystemRouteRoute
    }
  }
}

interface SystemRouteRouteChildren {
  SystemIndexRoute: typeof SystemIndexRoute
  SystemUsersMeRoute: typeof SystemUsersMeRoute
  SystemTeamsTeamIdSettingsRoute: typeof SystemTeamsTeamIdSettingsRoute
  SystemTeamsTeamIdIndexRoute: typeof SystemTeamsTeamIdIndexRoute
}

const SystemRouteRouteChildren: SystemRouteRouteChildren = {
  SystemIndexRoute: SystemIndexRoute,
  SystemUsersMeRoute: SystemUsersMeRoute,
  SystemTeamsTeamIdSettingsRoute: SystemTeamsTeamIdSettingsRoute,
  SystemTeamsTeamIdIndexRoute: SystemTeamsTeamIdIndexRoute,
}

const SystemRouteRouteWithChildren = SystemRouteRoute._addFileChildren(
  SystemRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthRegisterRoute: AuthRegisterRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SystemRouteRoute: SystemRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
